# 4. Perform the following operations using Python on the Heart Diseases data set
- a. Data cleaning
- b. Data integration
- c. Data transformation
- d. Error correcting
- e. Data model building

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("heart.csv")   
df

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

# a. Data Cleaning

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trtbps    303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalachh  303 non-null    int64
 8   exng      303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slp       303 non-null    int64
 11  caa       303 non-null    int64
 12  thall     303 non-null    int64
 13  output    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [4]:
# Check missing values
df.isnull().sum()

age         0
sex         0
cp          0
trtbps      0
chol        0
fbs         0
restecg     0
thalachh    0
exng        0
oldpeak     0
slp         0
caa         0
thall       0
output      0
dtype: int64

In [5]:
# Remove duplicates
df.drop_duplicates(inplace=True)
df

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [463]:
# Count ,min,max ,etc of each column
df.describe()

,age,sex,cp,trtbps,chol,fbs,restecg,thalachh,exng,oldpeak,slp,caa,thall,output
count,302.00000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000
mean,54.42053,0.682119,0.963576,131.602649,246.500000,0.149007,0.526490,149.569536,0.327815,1.043046,1.397351,0.718543,2.314570,0.543046
std,9.04797,0.466426,1.032044,17.563394,51.753489,0.356686,0.526027,22.903527,0.470196,1.161452,0.616274,1.006748,0.613026,0.498970
min,29.00000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.00000,0.000000,0.000000,120.000000,211.000000,0.000000,0.000000,133.250000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,55.50000,1.000000,1.000000,130.000000,240.500000,0.000000,1.000000,152.500000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.00000,1.000000,2.000000,140.000000,274.750000,0.000000,1.000000,166.000000,1.000000,1.600000,2.000000,1.000000,3.000000,1.000000
max,77.00000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

# b. Data Integration

In [6]:
# Create subset 1
sub1 = df[['age', 'sex', 'cp']]
sub1.head()

   age  sex  cp
0   63    1   3
1   37    1   2
2   41    0   1
3   56    1   1
4   57    0   0

In [7]:
# Create subset 2
sub2 = df[['chol', 'trtbps', 'thalachh']]
sub2.head()

   chol  trtbps  thalachh
0   233     145       150
1   250     130       187
2   204     130       172
3   236     120       178
4   354     120       163

In [8]:
# Merge using index
df_integrated = pd.merge(sub1, sub2, left_index=True, right_index=True)
df_integrated.head()

   age  sex  cp  chol  trtbps  thalachh
0   63    1   3   233     145       150
1   37    1   2   250     130       187
2   41    0   1   204     130       172
3   56    1   1   236     120       178
4   57    0   0   354     120       163

# c. Data Transformation

In [9]:
# Feature Scaling - Normalize numeric columns
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() # Scaling range is 0 to 1
numeric_cols = ['age','trtbps','chol','thalachh','oldpeak']

df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [10]:
df[numeric_cols]

          age    trtbps      chol  thalachh   oldpeak
0    0.708333  0.481132  0.244292  0.603053  0.370968
1    0.166667  0.339623  0.283105  0.885496  0.564516
2    0.250000  0.339623  0.178082  0.770992  0.225806
3    0.562500  0.245283  0.251142  0.816794  0.129032
4    0.583333  0.245283  0.520548  0.702290  0.096774
..        ...       ...       ...       ...       ...
298  0.583333  0.433962  0.262557  0.396947  0.032258
299  0.333333  0.150943  0.315068  0.465649  0.193548
300  0.812500  0.471698  0.152968  0.534351  0.548387
301  0.583333  0.339623  0.011416  0.335878  0.193548
302  0.583333  0.339623  0.251142  0.786260  0.000000

[302 rows x 5 columns]

# d. Error Correction

In [11]:
# Example: remove negative pollutant values
for col in numeric_cols:
    df[col] = df[col].apply(lambda x: x if x >= 0 else np.nan)

In [12]:
# fill NaN again after this
df[numeric_cols] = df[numeric_cols].ffill().bfill()

In [13]:
# Shape of df before removing outliers
df.shape

(302, 14)

In [14]:
# Remove outliers using IQR
Q1 = df[numeric_cols].quantile(0.25)
Q3 = df[numeric_cols].quantile(0.75)
IQR = Q3 - Q1

df = df[~((df[numeric_cols] < (Q1 - 1.5 * IQR)) | 
          (df[numeric_cols] > (Q3 + 1.5 * IQR))).any(axis=1)]

In [15]:
# Shape of df after removing outliers
df.shape

(283, 14)

In [16]:
# Another method to check outlier - should return all columns 0
outliers_check = ((df[numeric_cols] < (Q1 - 1.5 * IQR)) | 
                  (df[numeric_cols] > (Q3 + 1.5 * IQR))).sum()

print(outliers_check)

age         0
trtbps      0
chol        0
thalachh    0
oldpeak     0
dtype: int64

# e. Model Building

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [18]:
# Features & target
X = df.drop(columns=['output'])
y = df['output']

In [19]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [20]:
# Model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [21]:
# Prediction
y_pred = model.predict(X_test)

In [22]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7894736842105263

In [23]:
# Classification Report (Optional)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Classification Report:

              precision    recall  f1-score   support

           0       0.86      0.67      0.75        27
           1       0.75      0.90      0.82        30

    accuracy                           0.79        57
   macro avg       0.80      0.78      0.78        57
weighted avg       0.80      0.79      0.79        57

# classification_report gives:

- Precision : correctness of positive predictions
- Recall : ability to find all positives
- F1-score : balance of precision & recall
- Support : number of samples